### ISSUE TITLE
请教一下 react-native-parallax-swiper 的 vertical属性是怎样在安卓中实现的

### ISSUE THREAD

**Issue by wjiangwang** [Jon-Millent/douyin#3]
我在 react-native-parallax-swiper 的库中看到 垂直滑动的属性仅支持IOS ，自己也测试了下，发现在安卓中垂直滑动确实不行，用你的react-native-parallax-swiper 覆盖我的 ，也没成功，是需要在哪里设置么

**Comment by Jon-Millent** [comment]
刚看到，不好意思哈。这个react-native-parallax-swiper是我下载到本地魔改过的，在`douyin/src/util/react-native-parallax-swiper/` 这个地方
